import { jsPDF } from "jspdf";

import type {
  AdjudicationFormData,
  RehearsalPlanFormData,
  PerformanceProgramFormData,
  PortfolioAssessmentFormData,
  ArtDiscipline,
} from "../types/creative-arts-forms";

// ─── Export Data Interfaces ───

export interface AdjudicationExportData {
  formName: string;
  grade: string;
  artDiscipline: ArtDiscipline;
  description: string;
  formData: AdjudicationFormData;
  schoolName?: string;
  eventName?: string;
  date?: string;
}

export interface RehearsalExportData {
  formName: string;
  grade: string;
  artDiscipline: ArtDiscipline;
  description: string;
  formData: RehearsalPlanFormData;
  schoolName?: string;
  teacherName?: string;
  date?: string;
}

export interface ProgramExportData {
  formName: string;
  grade: string;
  artDiscipline: ArtDiscipline;
  description: string;
  formData: PerformanceProgramFormData;
  schoolName?: string;
  date?: string;
}

export interface PortfolioExportData {
  formName: string;
  grade: string;
  artDiscipline: ArtDiscipline;
  description: string;
  formData: PortfolioAssessmentFormData;
  schoolName?: string;
  teacherName?: string;
  studentName?: string;
  date?: string;
}

// ─── Style Constants ───

const HEADER_COLOR = [88, 28, 135] as const;
const SECTION_COLOR = [107, 33, 168] as const;
const TABLE_HEADER_BG = [243, 232, 255] as const;
const ALT_ROW_BG = [249, 250, 251] as const;
const LINE_HEIGHT = 5;
const MARGIN = 15;

// ─── Shared Helpers ───

function createDoc() {
  return new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
}

function getPageWidth(doc: jsPDF) {
  return doc.internal.pageSize.getWidth();
}

function getPageHeight(doc: jsPDF) {
  return doc.internal.pageSize.getHeight();
}

function getContentWidth(doc: jsPDF) {
  return getPageWidth(doc) - MARGIN * 2;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > getPageHeight(doc) - MARGIN) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function drawSectionHeader(
  doc: jsPDF,
  y: number,
  title: string
): number {
  const contentWidth = getContentWidth(doc);
  y = checkPageBreak(doc, y, 10);
  doc.setFillColor(...SECTION_COLOR);
  doc.rect(MARGIN, y, contentWidth, 7, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(title, MARGIN + 3, y + 5);
  doc.setTextColor(0, 0, 0);
  return y + 9;
}

function drawFooter(doc: jsPDF, label: string) {
  const totalPages = doc.getNumberOfPages();
  const pageWidth = getPageWidth(doc);
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by MwalimuKit  --  ${label}  --  Page ${i} of ${totalPages}`,
      pageWidth / 2,
      getPageHeight(doc) - 8,
      { align: "center" }
    );
  }
}

function drawBlankLines(
  doc: jsPDF,
  y: number,
  count: number,
  label?: string
): number {
  const pageWidth = getPageWidth(doc);
  y = checkPageBreak(doc, y, count * 6 + (label ? 8 : 0));
  if (label) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(120, 120, 120);
    doc.text(label, MARGIN + 3, y + 2);
    doc.setTextColor(0, 0, 0);
    y += 5;
  }
  for (let i = 0; i < count; i++) {
    y = checkPageBreak(doc, y, 6);
    doc.setDrawColor(200, 200, 200);
    doc.line(MARGIN + 3, y, pageWidth - MARGIN - 3, y);
    y += 6;
  }
  return y + 3;
}

function drawWrappedText(
  doc: jsPDF,
  y: number,
  text: string,
  fontSize = 9,
  fontStyle: "normal" | "bold" | "italic" = "normal"
): number {
  const contentWidth = getContentWidth(doc);
  doc.setFontSize(fontSize);
  doc.setFont("helvetica", fontStyle);
  const lines = doc.splitTextToSize(text, contentWidth - 6);
  let lineIdx = 0;
  while (lineIdx < lines.length) {
    const availableLines = Math.floor(
      (getPageHeight(doc) - MARGIN - y) / LINE_HEIGHT
    );
    const chunk = lines.slice(lineIdx, lineIdx + Math.max(1, availableLines));
    doc.text(chunk, MARGIN + 3, y + 2);
    y += chunk.length * LINE_HEIGHT + 2;
    lineIdx += chunk.length;
    if (lineIdx < lines.length) {
      doc.addPage();
      y = MARGIN;
    }
  }
  return y + 2;
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 1. ADJUDICATION / SCORING FORM
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export function generateAdjudicationFormPdf(
  data: AdjudicationExportData
): ArrayBuffer {
  const doc = createDoc();
  const pageWidth = getPageWidth(doc);
  const contentWidth = getContentWidth(doc);
  let y = MARGIN;

  // ─── School Name ───
  if (data.schoolName) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(40, 40, 40);
    doc.text(data.schoolName.toUpperCase(), pageWidth / 2, y, {
      align: "center",
    });
    y += 7;
  }

  // ─── Title ───
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  doc.text("ADJUDICATION / SCORING FORM", pageWidth / 2, y, {
    align: "center",
  });
  doc.setTextColor(0, 0, 0);
  y += 6;

  // Subtitle (form name)
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const titleLines = doc.splitTextToSize(data.formName, contentWidth);
  doc.text(titleLines, pageWidth / 2, y, { align: "center" });
  y += titleLines.length * 5 + 4;

  // ─── Event Info ───
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  if (data.formData.eventContext) {
    const ctxLines = doc.splitTextToSize(
      `Event: ${data.formData.eventContext}`,
      contentWidth - 6
    );
    doc.text(ctxLines, MARGIN + 3, y);
    y += ctxLines.length * LINE_HEIGHT + 1;
  }
  if (data.date) {
    doc.text(`Date: ${data.date}`, MARGIN + 3, y);
    y += 5;
  }
  doc.text(
    `Category: ${data.formData.category}  |  Grade: ${data.grade}  |  Discipline: ${data.artDiscipline}`,
    MARGIN + 3,
    y
  );
  y += 8;

  // ─── Blank Fields ───
  doc.setDrawColor(180, 180, 180);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  doc.text("Performer / Group Name:", MARGIN + 3, y);
  doc.line(MARGIN + 50, y, pageWidth - MARGIN - 3, y);
  y += 7;

  doc.text("School / Institution:", MARGIN + 3, y);
  doc.line(MARGIN + 45, y, pageWidth - MARGIN - 3, y);
  y += 7;

  doc.text("Category Number:", MARGIN + 3, y);
  doc.line(MARGIN + 40, y, pageWidth - MARGIN - 3, y);
  y += 10;

  // ─── Judging Criteria Table ───
  y = drawSectionHeader(doc, y, "JUDGING CRITERIA");

  // Table header
  const colCriterion = MARGIN;
  const colDesc = MARGIN + 50;
  const colMax = pageWidth - MARGIN - 30;
  const colScore = pageWidth - MARGIN - 15;

  y = checkPageBreak(doc, y, 10);
  doc.setFillColor(...TABLE_HEADER_BG);
  doc.rect(MARGIN, y, contentWidth, 7, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  doc.text("Criterion", colCriterion + 2, y + 5);
  doc.text("Description", colDesc + 2, y + 5);
  doc.text("Max", colMax + 2, y + 5);
  doc.text("Score", colScore + 2, y + 5);
  doc.setTextColor(0, 0, 0);
  y += 9;

  // Table rows
  data.formData.judgingCriteria.forEach((crit, idx) => {
    const descLines = doc.splitTextToSize(
      crit.description,
      colMax - colDesc - 6
    );
    const critLines = doc.splitTextToSize(crit.criterion, 46);
    const rowHeight = Math.max(critLines.length, descLines.length) * LINE_HEIGHT + 4;

    y = checkPageBreak(doc, y, rowHeight);

    // Alternate row background
    if (idx % 2 === 0) {
      doc.setFillColor(...ALT_ROW_BG);
      doc.rect(MARGIN, y - 1, contentWidth, rowHeight, "F");
    }

    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text(critLines, colCriterion + 2, y + 3);
    doc.setFont("helvetica", "normal");
    doc.text(descLines, colDesc + 2, y + 3);
    doc.text(String(crit.maxScore), colMax + 4, y + 3);

    // Score box
    doc.setDrawColor(180, 180, 180);
    doc.rect(colScore, y, 14, rowHeight - 2);

    y += rowHeight;
  });
  y += 4;

  // ─── Comment Sections ───
  data.formData.commentSections.forEach((section) => {
    y = drawSectionHeader(doc, y, section.label.toUpperCase());
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(120, 120, 120);
    doc.text(section.purpose, MARGIN + 3, y + 1);
    doc.setTextColor(0, 0, 0);
    y += 5;
    y = drawBlankLines(doc, y, 4);
  });

  // ─── Total Score ───
  y = checkPageBreak(doc, y, 18);
  doc.setFillColor(...TABLE_HEADER_BG);
  doc.rect(pageWidth - MARGIN - 60, y, 60, 10, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  doc.text("TOTAL SCORE:", pageWidth - MARGIN - 58, y + 7);
  doc.setDrawColor(...SECTION_COLOR);
  doc.rect(pageWidth - MARGIN - 18, y + 1, 16, 8);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(`/ ${data.formData.totalPossibleScore}`, pageWidth - MARGIN - 16, y + 6);
  doc.setTextColor(0, 0, 0);
  y += 16;

  // ─── Adjudicator Signature ───
  y = checkPageBreak(doc, y, 20);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setDrawColor(180, 180, 180);

  doc.text("Adjudicator Name:", MARGIN + 3, y);
  doc.line(MARGIN + 42, y, pageWidth / 2 - 5, y);
  doc.text("Signature:", pageWidth / 2 + 5, y);
  doc.line(pageWidth / 2 + 28, y, pageWidth - MARGIN - 3, y);
  y += 8;

  doc.text("Date:", MARGIN + 3, y);
  doc.line(MARGIN + 18, y, MARGIN + 60, y);
  y += 5;

  // ─── Footer ───
  drawFooter(doc, "Adjudication Form");

  return doc.output("arraybuffer");
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 2. REHEARSAL / PRACTICE PLAN
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export function generateRehearsalPlanPdf(
  data: RehearsalExportData
): ArrayBuffer {
  const doc = createDoc();
  const pageWidth = getPageWidth(doc);
  const contentWidth = getContentWidth(doc);
  let y = MARGIN;

  // ─── School Name ───
  if (data.schoolName) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(40, 40, 40);
    doc.text(data.schoolName.toUpperCase(), pageWidth / 2, y, {
      align: "center",
    });
    y += 7;
  }

  // ─── Title ───
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  doc.text("REHEARSAL / PRACTICE PLAN", pageWidth / 2, y, {
    align: "center",
  });
  doc.setTextColor(0, 0, 0);
  y += 6;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const titleLines = doc.splitTextToSize(data.formName, contentWidth);
  doc.text(titleLines, pageWidth / 2, y, { align: "center" });
  y += titleLines.length * 5 + 6;

  // ─── Info Box ───
  y = checkPageBreak(doc, y, 20);
  doc.setFillColor(...TABLE_HEADER_BG);
  doc.rect(MARGIN, y, contentWidth, 16, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Ensemble: ${data.formData.ensembleType}`,
    MARGIN + 3,
    y + 5
  );
  doc.text(
    `Duration: ${data.formData.duration} minutes`,
    pageWidth / 2 + 5,
    y + 5
  );
  doc.text(
    `Date: ${data.date || "_______________"}`,
    MARGIN + 3,
    y + 12
  );
  doc.text(
    `Teacher: ${data.teacherName || "_______________"}`,
    pageWidth / 2 + 5,
    y + 12
  );
  y += 20;

  // ─── Objectives ───
  y = drawSectionHeader(doc, y, "OBJECTIVES");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  data.formData.rehearsalObjectives.forEach((obj, idx) => {
    const text = `${idx + 1}. ${obj}`;
    const lines = doc.splitTextToSize(text, contentWidth - 8);
    y = checkPageBreak(doc, y, lines.length * LINE_HEIGHT + 2);
    doc.text(lines, MARGIN + 3, y + 2);
    y += lines.length * LINE_HEIGHT + 1;
  });
  y += 4;

  // ─── Warm-Up Activities Table ───
  y = drawSectionHeader(doc, y, "WARM-UP ACTIVITIES");

  y = checkPageBreak(doc, y, 10);
  doc.setFillColor(...TABLE_HEADER_BG);
  doc.rect(MARGIN, y, contentWidth, 7, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  doc.text("Activity", MARGIN + 3, y + 5);
  doc.text("Duration", pageWidth - MARGIN - 25, y + 5);
  doc.setTextColor(0, 0, 0);
  y += 9;

  data.formData.warmUpActivities.forEach((act, idx) => {
    const lines = doc.splitTextToSize(act.activity, contentWidth - 35);
    const rowH = lines.length * LINE_HEIGHT + 3;
    y = checkPageBreak(doc, y, rowH);
    if (idx % 2 === 0) {
      doc.setFillColor(...ALT_ROW_BG);
      doc.rect(MARGIN, y - 1, contentWidth, rowH, "F");
    }
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(lines, MARGIN + 3, y + 3);
    doc.text(`${act.duration} min`, pageWidth - MARGIN - 23, y + 3);
    y += rowH;
  });
  y += 4;

  // ─── Repertoire Table ───
  y = drawSectionHeader(doc, y, "REPERTOIRE");

  y = checkPageBreak(doc, y, 10);
  doc.setFillColor(...TABLE_HEADER_BG);
  doc.rect(MARGIN, y, contentWidth, 7, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  const repColTitle = MARGIN;
  const repColComposer = MARGIN + 65;
  const repColFocus = MARGIN + 115;
  doc.text("Title", repColTitle + 3, y + 5);
  doc.text("Composer", repColComposer + 3, y + 5);
  doc.text("Focus Area", repColFocus + 3, y + 5);
  doc.setTextColor(0, 0, 0);
  y += 9;

  data.formData.repertoire.forEach((item, idx) => {
    const titleText = doc.splitTextToSize(item.title, 60);
    const focusText = doc.splitTextToSize(item.focus, contentWidth - 118);
    const rowH =
      Math.max(titleText.length, focusText.length) * LINE_HEIGHT + 3;
    y = checkPageBreak(doc, y, rowH);
    if (idx % 2 === 0) {
      doc.setFillColor(...ALT_ROW_BG);
      doc.rect(MARGIN, y - 1, contentWidth, rowH, "F");
    }
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(titleText, repColTitle + 3, y + 3);
    doc.text(item.composer || "-", repColComposer + 3, y + 3);
    doc.text(focusText, repColFocus + 3, y + 3);
    y += rowH;
  });
  y += 4;

  // ─── Section Focus ───
  y = drawSectionHeader(doc, y, "SECTION FOCUS");

  data.formData.sectionFocus.forEach((section) => {
    y = checkPageBreak(doc, y, 15);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...SECTION_COLOR);
    doc.text(section.section, MARGIN + 3, y + 2);
    doc.setTextColor(0, 0, 0);
    y += 6;

    // Goals
    if (section.goals.length > 0) {
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text("Goals:", MARGIN + 5, y + 2);
      y += 5;
      doc.setFont("helvetica", "normal");
      section.goals.forEach((goal) => {
        const text = `\u2022 ${goal}`;
        const lines = doc.splitTextToSize(text, contentWidth - 14);
        y = checkPageBreak(doc, y, lines.length * LINE_HEIGHT + 1);
        doc.text(lines, MARGIN + 8, y + 2);
        y += lines.length * LINE_HEIGHT + 1;
      });
    }

    // Exercises
    if (section.exercises.length > 0) {
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text("Exercises:", MARGIN + 5, y + 2);
      y += 5;
      doc.setFont("helvetica", "normal");
      section.exercises.forEach((ex) => {
        const text = `\u2022 ${ex}`;
        const lines = doc.splitTextToSize(text, contentWidth - 14);
        y = checkPageBreak(doc, y, lines.length * LINE_HEIGHT + 1);
        doc.text(lines, MARGIN + 8, y + 2);
        y += lines.length * LINE_HEIGHT + 1;
      });
    }
    y += 4;
  });

  // ─── Cool Down ───
  y = drawSectionHeader(doc, y, "COOL DOWN");
  y = drawWrappedText(doc, y, data.formData.coolDown);

  // ─── Notes for Next Session ───
  y = drawSectionHeader(doc, y, "NOTES FOR NEXT SESSION");
  y = drawWrappedText(doc, y, data.formData.notesForNextSession);

  // ─── Footer ───
  drawFooter(doc, "Rehearsal Plan");

  return doc.output("arraybuffer");
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 3. PERFORMANCE PROGRAM
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export function generatePerformanceProgramPdf(
  data: ProgramExportData
): ArrayBuffer {
  const doc = createDoc();
  const pageWidth = getPageWidth(doc);
  const contentWidth = getContentWidth(doc);
  const fd = data.formData;
  let y = MARGIN;

  // ─── Cover Section ───
  y += 20;

  // Event name (large font)
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  const eventLines = doc.splitTextToSize(fd.eventName, contentWidth - 10);
  doc.text(eventLines, pageWidth / 2, y, { align: "center" });
  y += eventLines.length * 10 + 6;

  // Decorative line
  doc.setDrawColor(...HEADER_COLOR);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 40, y, pageWidth / 2 + 40, y);
  doc.setLineWidth(0.2);
  y += 8;

  // Venue
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  doc.text(fd.venue, pageWidth / 2, y, { align: "center" });
  y += 7;

  // Date & Time
  doc.setFontSize(11);
  doc.text(`${fd.eventDate}  |  ${fd.eventTime}`, pageWidth / 2, y, {
    align: "center",
  });
  y += 8;

  // School name
  if (data.schoolName) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(80, 80, 80);
    doc.text(data.schoolName, pageWidth / 2, y, { align: "center" });
    y += 7;
  }

  doc.setTextColor(0, 0, 0);
  y += 10;

  // ─── Program Header with decorative line ───
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  doc.text("PROGRAM", pageWidth / 2, y, { align: "center" });
  y += 3;
  doc.setDrawColor(...HEADER_COLOR);
  doc.setLineWidth(0.4);
  doc.line(MARGIN + 20, y, pageWidth - MARGIN - 20, y);
  doc.setLineWidth(0.2);
  doc.setTextColor(0, 0, 0);
  y += 8;

  // ─── Program Items Table ───
  const colOrder = MARGIN;
  const colTitle = MARGIN + 12;
  const colPerformer = MARGIN + 82;
  const colDuration = pageWidth - MARGIN - 20;

  // Table header
  y = checkPageBreak(doc, y, 10);
  doc.setFillColor(...HEADER_COLOR);
  doc.rect(MARGIN, y, contentWidth, 7, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("#", colOrder + 2, y + 5);
  doc.text("Item", colTitle + 2, y + 5);
  doc.text("Performer / Group", colPerformer + 2, y + 5);
  doc.text("Duration", colDuration + 2, y + 5);
  doc.setTextColor(0, 0, 0);
  y += 9;

  // Build a combined list of items and intermissions, sorted by order
  const intermissionSet = new Set(
    fd.intermissions.map((i) => i.afterItemNumber)
  );
  const intermissionMap = new Map(
    fd.intermissions.map((i) => [i.afterItemNumber, i])
  );

  fd.programItems.forEach((item, idx) => {
    const titleText = doc.splitTextToSize(item.title, 66);
    const performerText = doc.splitTextToSize(
      item.performerOrGroup,
      pageWidth - MARGIN - colPerformer - 24
    );
    const rowH =
      Math.max(titleText.length, performerText.length) * LINE_HEIGHT + 3;

    y = checkPageBreak(doc, y, rowH);
    if (idx % 2 === 0) {
      doc.setFillColor(...ALT_ROW_BG);
      doc.rect(MARGIN, y - 1, contentWidth, rowH, "F");
    }
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(String(item.order), colOrder + 3, y + 3);
    doc.setFont("helvetica", "bold");
    doc.text(titleText, colTitle + 2, y + 3);
    doc.setFont("helvetica", "normal");
    doc.text(performerText, colPerformer + 2, y + 3);
    doc.text(`${item.duration} min`, colDuration + 2, y + 3);
    y += rowH;

    // Check for intermission after this item
    if (intermissionSet.has(item.order)) {
      const inter = intermissionMap.get(item.order)!;
      const interH = 8;
      y = checkPageBreak(doc, y, interH);
      doc.setFillColor(243, 232, 255);
      doc.rect(MARGIN, y - 1, contentWidth, interH, "F");
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...SECTION_COLOR);
      doc.text(
        `--- INTERMISSION (${inter.duration} min) ---`,
        pageWidth / 2,
        y + 5,
        { align: "center" }
      );
      doc.setTextColor(0, 0, 0);
      y += interH;
    }
  });
  y += 6;

  // ─── Acknowledgments ───
  if (fd.acknowledgments) {
    y = drawSectionHeader(doc, y, "ACKNOWLEDGMENTS");
    y = drawWrappedText(doc, y, fd.acknowledgments);
  }

  // ─── Special Notes ───
  if (fd.specialNotes) {
    y = drawSectionHeader(doc, y, "NOTES");
    y = drawWrappedText(doc, y, fd.specialNotes);
  }

  // ─── Footer ───
  drawFooter(doc, "Performance Program");

  return doc.output("arraybuffer");
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 4. PORTFOLIO ASSESSMENT SHEET
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export function generatePortfolioAssessmentPdf(
  data: PortfolioExportData
): ArrayBuffer {
  const doc = createDoc();
  const pageWidth = getPageWidth(doc);
  const contentWidth = getContentWidth(doc);
  const fd = data.formData;
  let y = MARGIN;

  // ─── School Name ───
  if (data.schoolName) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(40, 40, 40);
    doc.text(data.schoolName.toUpperCase(), pageWidth / 2, y, {
      align: "center",
    });
    y += 7;
  }

  // ─── Title ───
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  doc.text("PORTFOLIO ASSESSMENT SHEET", pageWidth / 2, y, {
    align: "center",
  });
  doc.setTextColor(0, 0, 0);
  y += 6;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const titleLines = doc.splitTextToSize(data.formName, contentWidth);
  doc.text(titleLines, pageWidth / 2, y, { align: "center" });
  y += titleLines.length * 5 + 6;

  // ─── Student Info ───
  y = checkPageBreak(doc, y, 22);
  doc.setFillColor(...TABLE_HEADER_BG);
  doc.rect(MARGIN, y, contentWidth, 18, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Student Name: ${data.studentName || "______________________________"}`,
    MARGIN + 3,
    y + 6
  );
  doc.text(
    `Grade: ${data.grade}`,
    pageWidth / 2 + 10,
    y + 6
  );
  doc.text(
    `Date: ${data.date || "_______________"}`,
    MARGIN + 3,
    y + 14
  );
  doc.text(
    `Teacher: ${data.teacherName || "_______________"}`,
    pageWidth / 2 + 10,
    y + 14
  );
  y += 22;

  // ─── Portfolio Type ───
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(`Portfolio Type: `, MARGIN + 3, y);
  doc.setFont("helvetica", "normal");
  doc.text(fd.portfolioType, MARGIN + 35, y);
  y += 7;

  // ─── Required Components (Checklist) ───
  y = drawSectionHeader(doc, y, "REQUIRED COMPONENTS");

  fd.requiredComponents.forEach((comp, idx) => {
    const descLines = doc.splitTextToSize(
      `${comp.component} - ${comp.description}`,
      contentWidth - 14
    );
    const rowH = descLines.length * LINE_HEIGHT + 3;
    y = checkPageBreak(doc, y, rowH);

    if (idx % 2 === 0) {
      doc.setFillColor(...ALT_ROW_BG);
      doc.rect(MARGIN, y - 1, contentWidth, rowH, "F");
    }

    // Checkbox square
    doc.setDrawColor(180, 180, 180);
    doc.rect(MARGIN + 3, y + 0.5, 4, 4);

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(descLines, MARGIN + 10, y + 3);
    y += rowH;
  });
  y += 4;

  // ─── Assessment Criteria ───
  y = drawSectionHeader(doc, y, "ASSESSMENT CRITERIA");

  fd.assessmentCriteria.forEach((crit) => {
    // Criterion name
    y = checkPageBreak(doc, y, 15);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...SECTION_COLOR);
    doc.text(crit.criterion, MARGIN + 3, y + 2);
    doc.setTextColor(0, 0, 0);
    y += 7;

    // Rubric levels table header
    const colLevel = MARGIN + 2;
    const colDesc = MARGIN + 35;
    const colPoints = pageWidth - MARGIN - 28;
    const colCheck = pageWidth - MARGIN - 12;

    y = checkPageBreak(doc, y, 10);
    doc.setFillColor(...TABLE_HEADER_BG);
    doc.rect(MARGIN, y, contentWidth, 6, "F");
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...HEADER_COLOR);
    doc.text("Level", colLevel, y + 4);
    doc.text("Description", colDesc, y + 4);
    doc.text("Points", colPoints, y + 4);
    doc.text("Check", colCheck, y + 4);
    doc.setTextColor(0, 0, 0);
    y += 8;

    // Rubric rows
    crit.rubricLevels.forEach((level, lIdx) => {
      const descText = doc.splitTextToSize(
        level.description,
        colPoints - colDesc - 4
      );
      const rowH = descText.length * LINE_HEIGHT + 3;
      y = checkPageBreak(doc, y, rowH);

      if (lIdx % 2 === 0) {
        doc.setFillColor(...ALT_ROW_BG);
        doc.rect(MARGIN, y - 1, contentWidth, rowH, "F");
      }

      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text(level.level, colLevel, y + 3);
      doc.setFont("helvetica", "normal");
      doc.text(descText, colDesc, y + 3);
      doc.text(String(level.pointValue), colPoints + 4, y + 3);

      // Check box
      doc.setDrawColor(180, 180, 180);
      doc.rect(colCheck + 1, y + 0.5, 4, 4);

      y += rowH;
    });
    y += 4;
  });

  // ─── Score Summary ───
  y = drawSectionHeader(doc, y, "SCORE SUMMARY");

  // Header row
  y = checkPageBreak(doc, y, 10);
  doc.setFillColor(...TABLE_HEADER_BG);
  doc.rect(MARGIN, y, contentWidth, 6, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  doc.text("Criterion", MARGIN + 3, y + 4);
  doc.text("Score", pageWidth - MARGIN - 20, y + 4);
  doc.setTextColor(0, 0, 0);
  y += 8;

  fd.assessmentCriteria.forEach((crit, idx) => {
    const rowH = 7;
    y = checkPageBreak(doc, y, rowH);
    if (idx % 2 === 0) {
      doc.setFillColor(...ALT_ROW_BG);
      doc.rect(MARGIN, y - 1, contentWidth, rowH, "F");
    }
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(crit.criterion, MARGIN + 3, y + 4);
    // Blank score box
    doc.setDrawColor(180, 180, 180);
    doc.rect(pageWidth - MARGIN - 18, y, 14, 6);
    y += rowH;
  });

  // Total row
  y = checkPageBreak(doc, y, 8);
  doc.setFillColor(...TABLE_HEADER_BG);
  doc.rect(MARGIN, y, contentWidth, 8, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...HEADER_COLOR);
  doc.text("TOTAL", MARGIN + 3, y + 6);
  doc.setDrawColor(...SECTION_COLOR);
  doc.rect(pageWidth - MARGIN - 18, y + 1, 14, 6);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(`/ ${fd.totalPoints}`, pageWidth - MARGIN - 16, y + 5);
  doc.setTextColor(0, 0, 0);
  y += 12;

  // ─── Growth Indicators (Checklist) ───
  y = drawSectionHeader(doc, y, "GROWTH INDICATORS");

  fd.growthIndicators.forEach((indicator, idx) => {
    const lines = doc.splitTextToSize(indicator, contentWidth - 14);
    const rowH = lines.length * LINE_HEIGHT + 2;
    y = checkPageBreak(doc, y, rowH);

    if (idx % 2 === 0) {
      doc.setFillColor(...ALT_ROW_BG);
      doc.rect(MARGIN, y - 1, contentWidth, rowH, "F");
    }

    doc.setDrawColor(180, 180, 180);
    doc.rect(MARGIN + 3, y + 0.5, 4, 4);

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(lines, MARGIN + 10, y + 3);
    y += rowH;
  });
  y += 4;

  // ─── Reflection Prompts ───
  y = drawSectionHeader(doc, y, "REFLECTION PROMPTS");

  fd.reflectionPrompts.forEach((prompt, idx) => {
    const text = `${idx + 1}. ${prompt}`;
    const lines = doc.splitTextToSize(text, contentWidth - 8);
    y = checkPageBreak(doc, y, lines.length * LINE_HEIGHT + 20);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(lines, MARGIN + 3, y + 2);
    y += lines.length * LINE_HEIGHT + 3;
    // Blank lines for response
    y = drawBlankLines(doc, y, 3);
  });

  // ─── Teacher Comments ───
  y = drawSectionHeader(doc, y, "TEACHER COMMENTS");
  y = drawBlankLines(doc, y, 6);

  // ─── Signature Lines ───
  y = checkPageBreak(doc, y, 30);
  doc.setDrawColor(180, 180, 180);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  doc.text("Teacher Signature:", MARGIN + 3, y);
  doc.line(MARGIN + 42, y, pageWidth / 2 - 5, y);
  doc.text("Date:", pageWidth / 2 + 10, y);
  doc.line(pageWidth / 2 + 23, y, pageWidth - MARGIN - 3, y);
  y += 10;

  doc.text("Parent / Guardian:", MARGIN + 3, y);
  doc.line(MARGIN + 42, y, pageWidth / 2 - 5, y);
  doc.text("Date:", pageWidth / 2 + 10, y);
  doc.line(pageWidth / 2 + 23, y, pageWidth - MARGIN - 3, y);
  y += 5;

  // ─── Footer ───
  drawFooter(doc, "Portfolio Assessment");

  return doc.output("arraybuffer");
}
